name: Backtest WF

on:
  workflow_dispatch:     # lanzarlo a mano
  schedule:
    - cron: "15 0 * * *" # cada día a las 00:15 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backtest
        run: python backtest.py
      - name: Commit reports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/*
          if ! git diff --cached --quiet; then
            git commit -m "chore: backtest reports"
            git push
          fi
